//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсилио
{
    using System;
    using System.Collections.Generic;
    
    public partial class Жанр
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Жанр()
        {
            this.Оценённые = new HashSet<Оценённые>();
        }
    
        public int ID_жанра { get; set; }
        public string Название { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public string Популярность { get; set; }
        public double Рейтинг { get; set; }
        public int Количество_оценок { get; set; }
        public int ID_исполнителя { get; set; }
        public int ID_композитора { get; set; }
        public int ID_инструмента { get; set; }
        public string История { get; set; }
        public string Звучание { get; set; }
        public int картинка { get; set; }
    
        public virtual лого лого { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценённые> Оценённые { get; set; }
        public virtual Инструменты Инструменты { get; set; }
        public virtual Исполнители Исполнители { get; set; }
        public virtual Композиторы Композиторы { get; set; }
    }
}
