//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсилио
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исполнители
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Исполнители()
        {
            this.Жанр = new HashSet<Жанр>();
        }
    
        public int ID_исполнителя { get; set; }
        public string Псевдоним_исполнителя { get; set; }
        public string ФИО_исполнителя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Жанр> Жанр { get; set; }
    }
}
